-- Default Categories (global — user_id IS NULL)

insert into public.categories (name, type, icon, color, aliases, is_default) values
  ('Makanan', 'expense', '🍽️', '#ef4444', array[
    'jajan','makan','minum','kopi','nasi','cemilan','sarapan','mie','bakso','soto','masakan',
    'nasi goreng','indomie','sate','pecel','gudeg','rawon','siomay','batagor','pempek',
    'martabak','ayam','ikan','tempe','tahu','sayur','lauk','makan siang','makan malam',
    'sarapan pagi','cafe','restoran','warteg','angkringan','gorengan','bubur','ketoprak',
    'gado gado','rendang','opor','sambal','lalapan','sop','steak','pizza','burger',
    'kfc','mcd','wendys','gerobak','kaki lima','seblak','cilok','cilung','cuanki',
    'dimsum','ramen','sushi','gado','bubur ayam','nasi uduk','nasi padang','nasi kuning',
    'lontong','lotek','rujak','tahu bulat','telur','pisang goreng','es campur',
    'es teh','es jeruk','teh','susu','boba','thai tea','jus','smoothie','air mineral',
    'snack','roti','kue','coklat','eskrim','kripik','makaron','sosis','nuget',
    'indomie rebus','indomie goreng','seblak','sempol','pentol','cilok','basreng',
    'surabi','pukis','kue cubit','kue lapis','lumpur','kue bolu','donat','milkshake',
    '🍔','🍕','🥘','🍜','🍣','🥗','🍿','🍩','🍰','☕','🧋','🥡','🍝','🌮','🌯','🥟'
  ], true),
  ('Transport', 'expense', '🚗', '#f97316', array[
    'bensin','angkot','gojek','grab','ojek','bbm','taksi','bus','kereta','bengkel',
    'toll','parkir','pertalite','pertamax','solar','busway','mrt','lrt','krl',
    'ojol','maxim','topup e-money','isi saldo','kendaraan','spbu','naik','jalan jauh',
    'travel','shuttle','elf','mikrolet','kopaja','angkutan','kendaraan umum',
    'bensin motor','bensin mobil','isi bensin','tune up','service motor','service mobil',
    'ganti oli','ban','velg','helm','kaca film','stnk','sim','perpanjang stnk',
    'gocar','gofood delivery','grabcar','grabfood','shopee food','maxim car',
    'taxi online','ojek online','ojek pangkalan','ojek pasar','delivery',
    'tol','jalan tol','e money','flazz','bni tap','mandiri e money',
    '⛽','🚕','🚌','🚗','🛵','🚇','🅿️','🚘','✈️','🚢','🚲','🛴','🏍️'
  ], true),
  ('Hiburan', 'expense', '🎬', '#eab308', array[
    'nonton','film','game','musik','jalan','bioskop','konser','liburan',
    'netflix','spotify','youtube','steam','playstation','cafe','ngopi',
    'nongki','karaoke','billiard','futsal','badminton','renang','wisata',
    'tiket','wisata','pantai','gunung','hotel','penginapan','villa','camping',
    'jogging','lari','fitnes','gym','yoga','pilates','sepeda','gowes',
    'ml','mobile legend','pubg','free fire','valorant','genshin','cod',
    'playstation','nintendo','xbox','game online','game offline','voucher game',
    'topup game','diamond','skin','v-buck','gems','codashop','itemku','unipin',
    'nobar','movie','series','anime','drakor','drama','sinema','tv',
    'live music','jazz','festival','pameran','bazar','event','pesta',
    '🎮','🎯','🎪','🎤','🎸','🏊','⚽','🎥','🎧','🎟️','🏕️','🎳','🎰','🧩','🎨','🎭','📺'
  ], true),
  ('Belanja', 'expense', '🛒', '#22c55e', array[
    'belanja','baju','bulanan','sembako','pakaian','sepatu','tas',
    'alfamart','indomaret','supermarket','minimarket','online shop',
    'shopee','tokopedia','lazada','blibli','e-commerce','fashion','kosmetik',
    'skincare','aksesoris','makeup','parfum','body care','handuk','sprei',
    'baju koko','gamis','hijab','jilbab','sarung','peci','celana','jeans',
    'kaos','kemeja','jaket','sweater','hoodie','cardigan','blouse','rok',
    'dress','kebaya','batik','seragam','pakaian dalam','sandal','flat shoes',
    'sneakers','heels','boots','sepatu olahraga','jam tangan','gelang','kalung',
    'cincin','anting','tindik','piercing','tattoo',
    'furniture','lemari','meja','kursi','rak','lampu','hiasan','dekorasi',
    'elektronik','laptop','hp','handphone','charger','kabel','earphone','headset',
    'speaker','tv','kulkas','mesin cuci','kipas','ac','rice cooker','blender',
    'peralatan rumah tangga','alat masak','piring','gelas','panci','wajan',
    'ATK','alat tulis','kertas','pulpen','pensil','penggaris','stapler',
    'hewan peliharaan','kucing','anjing','burung','makanan kucing','pakan',
    'popok','diaper','sabun','shampoo','pasta gigi','sikat gigi','detergen',
    'pembersih','pewangi','lilin','insektisida','obat nyamuk',
    '🛒','👗','👟','🧴','🛍️','💄','🧢','👠','👜','👕','🧥','👖','🧸','🪴','🖼️','🕯️'
  ], true),
  ('Kesehatan', 'expense', '💊', '#3b82f6', array[
    'obat','dokter','klinik','rumah sakit','vitamin','cek','rs','puskesmas',
    'dokter gigi','mata','farmasi','apotek','berobat','sakit','medical',
    'bpjs','asuransi','konsultasi','periksa','tes darah','rontgen','usg',
    'operasi','rawat jalan','rawat inap','umum','gigi','spesialis',
    'kacamata','lensa','frame','softlens','kontolensa','reseptor',
    'suntik','vaksin','imunisasi','flu','batuk','demam','masuk angin',
    'maag','diare','migrain','pusing','alergi','gatal','kulit','jerawat',
    'obat jerawat','salep','krim','plaster','perban','masker','hand sanitizer',
    'hamil','melahirkan','kb','pil kb','suntik kb','susuk kb','spiral',
    'fisioterapi','pijat','refleksi','akupuntur','tradisional','jamu',
    'covid','test pack','kehamilan','kandungan',
    '💊','🏥','💉','🩺','🧬','🦷','👁️','🧪','🩹','🩻'
  ], true),
  ('Tagihan', 'expense', '📄', '#8b5cf6', array[
    'listrik','air','wifi','pulsa','internet','telpon','bpjs','pajak',
    'token listrik','pdam','indihome','telkomsel','tri','xl','axis',
    'by.u','pascabayar','abodemen','iuran','subsidi','stroom','pln',
    'pulsa listrik','isi listrik','listrik token','token token',
    'air pdam','air bersih','air pam','pdam bayar',
    'wifi bulanan','indihome bayar','first media','mytv','cable',
    'pulsa hp','pulsa telkomsel','pulsa xl','pulsa axis','pulsa three',
    'pulsa smart','pulsa im3','pulsa mentari','pulsa byu',
    'kuota','paket data','internet bulanan','wifi rumah',
    'netflix bulanan','spotify premium','youtube premium','icloud',
    'google one','dropbox','aws','domain','hosting','server',
    'angsuran','kredit','cicilan','kpr','kkb','pinjaman','utang',
    'bayar utang','bayar cicilan','cicilan motor','cicilan mobil',
    'kartu kredit','cc','tagihan kartu kredit','bank bills',
    '📱','💡','🌐','📺','💧','🔌','📡','🔋','⚡',
    'bpjs kesehatan','bpjs ketenagakerjaan','bpjs mandiri',
    'pajak bumi','pbb','pajak kendaraan','pajak mobil','pajak motor'
  ], true),
  ('Pendidikan', 'expense', '📚', '#ec4899', array[
    'kuliah','buku','kursus','les','pelatihan','modul','uts','uas','skripsi',
    'sidang','praktikum','semester','spp','ukt','daftar ulang','diklat',
    'seminar','workshop','sekolah','sd','smp','sma','tk','paud','playgroup',
    'pondok','pesantren','madrasah','boarding school','bimbel',
    'privat','guru les','les matematika','les bahasa','les inggris',
    'les komputer','les musik','les vokal','les dance','les tari',
    'taman kanak','perlengkapan sekolah','seragam sekolah','buku pelajaran',
    'lks','alat tulis sekolah','tas sekolah','sepatu sekolah',
    'pendaftaran','daftar ulang','formulir','uang gedung','uang pangkal',
    'sumbangan','iuran sekolah','ospek','pkk','study tour','field trip',
    'pkl','magang','internship','mbkm','kampus merdeka',
    'ijazah','toefl','ielts','sertifikat','sertifikasi','lisensi',
    'tugas akhir','ta','tesis','disertasi','jurnal','publikasi',
    'beasiswa','bidikmisi','kip kuliah','kartu indonesia pintar',
    '📚','🎓','✏️','📖','🖊️','🎒','📐','📏','🧮','📝','🗂️'
  ], true),
  ('Lainnya (Expense)', 'expense', '❓', '#6b7280', array[
    'lainnya','lain','dll','etc','lain','uncategorized','misc',
    'donasi','amal','sumbangan','sedekah','zakat','infaq','shodaqoh',
    'dana','kas','iuran rt','iuran rw','keamanan','kebersihan',
    'pernikahan','undangan','nyumbang','sumbangan nikah','sumbangan kematian',
    'asuransi','prudential','manulife','aia','sequis',
    'koperasi','simpan pinjam','arisan','arisan bulanan',
    'biaya admin','admin bank','transfer biaya','materai',
    'topup e wallet','gopay','ovo','dana','link aja','shopeepay',
    'qris','mbanking','atm','tarik tunai','setor tunai',
    'denda','telat bayar','penalti','tilang','tiket tilang',
    '❓','📦','🎁','🎀','📌'
  ], true),
  ('Gaji', 'income', '💰', '#22c55e', array[
    'gaji','salary','upah','honor','pendapatan','income','bulanan','thr','bonus',
    'gaji bulanan','gaji pokok','take home pay','thp','gaji bersih',
    'honor mengajar','honor dosen','honor guru','honor pembicara',
    'upah harian','upah borongan','upah lembur','lembur','overtime',
    'tunjangan','tunjangan makan','tunjangan transport','tunjangan anak',
    'tunjangan istri','tunjangan jabatan','tunjangan fungsional',
    'insentif','komisi','performa bonus','tahunan','bonus tahunan',
    'rapel','kenaikan gaji','pensiun','dana pensiun',
    'thr lebaran','thr natal','bonus lebaran',
    'dividen','deviden','saham','reksadana','investasi','cuan',
    'bagi hasil','profit sharing','hasil usaha','laba',
    'uang saku','jatah','jajan bulanan',
    '💰','💼','📊','💳','🏦','📈','💵','🧾','📋'
  ], true),
  ('Freelance', 'income', '💻', '#3b82f6', array[
    'freelance','project','proyek','order','job','fiverr','upwork','sasana',
    'design','coding','desain','web','aplikasi','konten','nulis',
    'ngoding','programming','developer','frontend','backend','fullstack',
    'ui ux','uiux','figma','sketch','photoshop','illustrator','canva',
    'logo','branding','brochure','flyer','poster','banner','spanduk',
    'video editing','editing','premiere','after effect','capcut',
    'fotografi','photo','foto','shoot','wedding photography',
    'copywriting','nulis artikel','content writer','blogger','vlogger',
    'youtuber','tiktok','ig','influencer','endorse','sponsor','brand deal',
    'afiliasi','affiliate','link aff','shopee aff','tokopedia aff',
    'dropship','dropshipper','reseller','jualan online','online shop',
    'makelar','properti','tanah','rumah','jual rumah','jual tanah',
    'komisi jual','fee','jasa','konsultan','konsultasi','mentor','coach',
    'ngajar','privat','les privat','guru privat','tutor',
    'translator','translate','terjemah','interpreter',
    'art','seni','lukis','sketsa','custom','handmade','craft',
    'bisnis online','ecommerce','toko online','webinar','training',
    '💻','🖥️','📱','🎨','📷','🎬','✍️','🛠️','🔧','👨‍💻','👩‍💻'
  ], true),
  ('Kiriman', 'income', '📨', '#f97316', array[
    'kiriman','transfer','dari mama','dari ort','dari ayah','dari ibu',
    'dari pacar','hadiah','kado','rejeki','ampau','angpau',
    'dari kakak','dari adik','dari saudara','dari kakek','dari nenek',
    'dari om','dari tante','dari paman','dari bibi',
    'dari keluarga','dari orang tua','dari ortu','dari bokap','dari nyokap',
    'dari suami','dari istri','dari anak','dari sepupu',
    'reimburse','reimbursement','klaim','pengembalian dana','refund',
    'hutang dikembalin','bayar hutang','pelunasan','angsuran masuk',
    'pinjaman','minjem','dipinjemin','utangan','uang muka','dp',
    'geratis','free','diberi','dapet','dikasih','dapat bonus',
    'doorprize','undian','lotre','kupon menang','menang lomba',
    'warisan','pusaka','hibah','pemberian',
    'brangkas','tabungan','narik deposito','deposito','bunga bank',
    'hasil nabung','cairin tabungan','ambil tabungan','ambil uang',
    '📨','🎁','💸','🤲','🧧','💝','📬','✉️'
  ], true),
  ('Lainnya (Income)', 'income', '❓', '#6b7280', array[
    'lainnya','lain','dll','etc','uncategorized','misc'
  ], true)
on conflict (name, type) where user_id is null do nothing;
